### ISSUE TITLE
Making the App Responsive and Look Good on Mobile Devices

### ISSUE THREAD

**Issue by MarcoMorawec** [lantrinhca/splurty#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by lantrinhca** [comment]
Hi Marco,
I added the meta tag <meta name="viewport" content="width=device-width, initial-scale=1"> to the application.html.erb, but I didn't see any changes.

**Comment by lantrinhca** [comment]
OK, I think that's fixed with meta name="viewport" content="width=device-width, initial-scale=1"
into the head tag.

**Comment by MarcoMorawec** [comment]
@lantrinhca :+1: 

Make sure you close the issue, now that you've solved it.
